  services:
     app:
       container_name: web
       restart: always
       build: ./app
       ports:
           - "8000:8000"
       command: gunicorn app:app -b :8000 --name app --log-level=debug --log-file=-

     nginx:
       container_name: nginx
       restart: always
       build: ./nginx
       ports:
           - "80:80"
           - 443:443
       depends_on:
           - app




