version: '3'

services:
  web:
    build: ./web
    ports:
      - "80:80"
    environment:
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=development
    command: flask run --host=0.0.0.0 --port=80

