version: '3.7'
services:

     app:
       container_name: web
       restart: always
       build: ./app
       ports:
           - "8000:8000"
       command: gunicorn app:app -b :8000 --name app --log-level=debug --log-file=-
       depends_on:
           - db    
       networks:
           - frontend
           - backend

     nginx:
       container_name: nginx
       restart: always
       build: ./nginx
       ports:
           - "80:80"
           - 443:443
       depends_on:
           - app
       networks:
           - frontend

     db:

       image: mongo
       container_name: mongo
       restart: unless-stopped
       command: mongod --auth
       ports:
           - "27017:27017"
       environment:
           MONGO_INITDB_ROOT_USERNAME: root
           MONGO_INITDB_ROOT_PASSWORD: rootpassword
           MONGODB_DATA_DIR: /data/db
       networks:
           - backend
           
networks:
      frontend:
        driver: bridge
      backend:
        driver: bridge

