version: '3.7'
services:
     app:
       container_name: web
       restart: always
       build: ./app
       ports:
           - "8000:8000"
       command: gunicorn app:app -b :8000 --name app --log-level=debug --log-file=-
       environment:
        APP_ENV: "prod"
        APP_DEBUG: "False"
        APP_PORT: 5000
        MONGODB_DATABASE: app_db
        MONGODB_USERNAME: test
        MONGODB_PASSWORD: test
        MONGODB_HOSTNAME: mongodb
       depends_on:
           - db
       networks:
           - frontend
           - backend
           

     nginx:
       container_name: nginx
       restart: always
       build: ./nginx
       ports:
           - "80:80"
           - 443:443
       depends_on:
           - app
       networks:
           - frontend


     db:
#      image: mongo:latest
       image: mongo:4.0.8
       container_name: mongo
       restart: unless-stopped
       command: mongod --auth
       ports:
           - "27017:27017"
       environment:
           MONGO_INITDB_ROOT_USERNAME: test
           MONGO_INITDB_ROOT_PASSWORD: test
           MONGODB_DATA_DIR: /data/db
       networks:
           - backend

networks:
      frontend:
        driver: bridge
      backend:
        driver: bridge





